### ISSUE TITLE
This relative module was not found

### ISSUE THREAD

**Issue by diomed** [DesignRevision/shards-dashboard-vue#1]
Upon installation I get this error:

This relative module was not found:
`* ./scss/shards-dashboards.scss in ./src/main.js`

**Comment by nickvasdev** [comment]
@diomed Whoops! 😅This is now [fixed](https://github.com/DesignRevision/shards-dashboard-vue/commit/db291be87ecb6ce54925e6d17e8d6cd1928a02ee). Sorry for the inconvenience!
