### ISSUE TITLE
v-model

### ISSUE THREAD

**Issue by diomed** [DesignRevision/shards-dashboard-vue#2]
hi

would you, please, add v-model for user profile so items entered in Account Details would automatically display on card?

[also would be cool if blog posts were actually searchable]

https://screenshotscdn.firefoxusercontent.com/images/55bc0824-afa2-4fc0-95cb-281d2d82076b.png

**Comment by diomed** [comment]
soooo ⁉️

**Comment by nickvasdev** [comment]
@diomed Hi there! 👋 I apologize for the delay. 😄 

While I understand how this might prove to be useful for some developers, I'm afraid both requests are quite opinionated and won't make it into the layout pack.

Everyone who uses the templates should be allowed to decide the underlying logic for herself/himself.
